#!/usr/bin/env bash
# Fails if any hand-authored doc hardcodes a tool count that no longer
# matches docs/status.generated.md (itself generated by gen-status.sh from
# the committed tool schema snapshots -- see that script's header). This
# script doesn't touch status.generated.md -- gen-status.sh --check already
# owns that file. It closes the gap found 2026-08-03
# (docs/plans/2026-08-03-product-truth-closure-plan.md): six other files
# still said "30 tools"/"22 tools" a full release after a 30->34 tool bump
# had already landed and status.generated.md had already been regenerated
# correctly -- gen-status.sh's own drift gate has no reach into these.
#
# Deliberately NOT a blanket `[0-9]+ tools` scan: this repo's own
# benchmarks/README.md prose mentions counts like "9 tools driven live over
# JSON-RPC" that have nothing to do with CALM's total tool inventory, and a
# blanket scan flags those as false-positive drift. Each pattern below is
# anchored to one of the specific phrasings the 6 known files actually use
# to state CALM's *total* tool count -- add a new pattern here if a future
# doc introduces a new phrasing, rather than loosening these.
#
# Usage:
#   scripts/check-doc-truth.sh   # print mismatches, exit 1 if any
set -euo pipefail
cd "$(dirname "$0")/.."

status_file="docs/status.generated.md"
if [ ! -f "$status_file" ]; then
    echo "check-doc-truth: $status_file missing -- run scripts/gen-status.sh first" >&2
    exit 1
fi

authoritative=$(grep -oE '## MCP tool inventory \([0-9]+ tools\)' "$status_file" \
    | grep -oE '[0-9]+')
if [ -z "$authoritative" ]; then
    echo "check-doc-truth: could not extract tool count from $status_file" >&2
    exit 1
fi

files=(
    README.md
    AGENTS.md
    llms.txt
    .claude-plugin/marketplace.json
    plugins/calm/.claude-plugin/plugin.json
    crates/calm-core/src/workflow.rs
)

# Each pattern must have exactly one capture group: the tool count digits.
patterns=(
    '[0-9]+ tools total'
    '[0-9]+ MCP tools'
    'exposing [0-9]+ tools'
    'All [0-9]+ tools'
    '[0-9]+ tools\. [0-9]+ stages'
    '[0-9]+ stages, [0-9]+ tools'
)

fail=0
for f in "${files[@]}"; do
    [ -f "$f" ] || continue
    for pat in "${patterns[@]}"; do
        while IFS= read -r match; do
            [ -n "$match" ] || continue
            # The count is always the number immediately (optionally via
            # " MCP ") before the literal word "tools" -- true for both
            # "N tools ..." and "... stages, N tools" shaped matches, so
            # this one extraction works for every pattern above without
            # needing to special-case which side of the match the digits
            # are on.
            n=$(echo "$match" | grep -oE '[0-9]+( MCP)? tools' | grep -oE '^[0-9]+')
            if [ "$n" != "$authoritative" ]; then
                echo "check-doc-truth: $f says \"$match\" but $status_file says $authoritative tools" >&2
                fail=1
            fi
        done < <(grep -ohE "$pat" "$f" || true)
    done
done

if [ "$fail" -ne 0 ]; then
    echo "check-doc-truth: update the numbers above (or regenerate $status_file if it's the stale one)" >&2
    exit 1
fi
echo "check-doc-truth: all hand-authored tool-count references match ($authoritative tools)."
