#!/usr/bin/env bash
# Generates docs/status.generated.md from executable sources -- the MCP
# tool inventory + write-path taxonomy come from
# crates/calm-server/src/__toolsnaps__/*.snap (the committed JSON schema
# snapshots tool_schemas_match_committed_snapshots already keeps honest
# against the real running tool schemas, including each tool's
# readOnlyHint/idempotentHint annotations), feature/language coverage comes
# from crates/calm-core/Cargo.toml's [features] table, and the guarantee-
# level catalog comes from docs/guarantee-levels.toml (hand-maintained, but
# its rendering into this file is still covered by the same --check gate --
# see docs/plans/2026-08-03-product-truth-closure-plan.md PR2). WS-13
# (docs/plans/2026-08-01-calm-adopt-from-vheatm-plan.md P3-2): CALM's own
# status must never drift the way VHEATM's own README ("pilot") drifted
# from its own registry ("complete") -- generate from a source another
# test already keeps honest, don't hand-type prose that nobody remembers
# to update.
#
# Deliberately excludes any wall-clock timestamp from the generated
# content: a timestamp would make `--check` fail on every run regardless
# of real content drift, defeating the point of a no-drift gate. The
# output is a pure function of the current repo state.
#
# Usage:
#   scripts/gen-status.sh          # regenerate docs/status.generated.md in place
#   scripts/gen-status.sh --check  # exit 1 if the committed file would change (CI drift gate)
#
# Requires: jq (already a CI dependency -- see .github/workflows/ci.yml's
# otel-http-features job for the other existing use).
set -euo pipefail
cd "$(dirname "$0")/.."

if ! command -v jq >/dev/null 2>&1; then
    echo "gen-status: jq not found -- install it first (apt-get install -y jq / brew install jq)" >&2
    exit 1
fi

out="docs/status.generated.md"
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

# jq gotcha guard: `//` treats a real `false` the same as `null` (both
# "falsy"), so `.annotations.readOnlyHint // true` would silently turn a
# genuine `false` into `true` -- exactly the boolean this script most
# needs to get right. Every extraction below compares against `== false`
# explicitly instead of relying on `//`.
tool_count=$(ls crates/calm-server/src/__toolsnaps__/*.snap 2>/dev/null | wc -l | tr -d ' ')

{
    echo "<!-- GENERATED by scripts/gen-status.sh -- do not hand-edit, re-run the script instead. -->"
    echo "# CALM status (generated)"
    echo
    echo "Source of truth: crates/calm-server/src/__toolsnaps__/*.snap (tool schemas +"
    echo "annotations) and crates/calm-core/Cargo.toml's \`[features]\` table. Not"
    echo "hand-maintained prose -- run \`scripts/gen-status.sh\` to refresh after any tool"
    echo "or feature-flag change; CI's \`gen-status.sh --check\` fails the build on drift."
    echo
    echo "## MCP tool inventory ($tool_count tools)"
    echo
    echo "| Tool | Write | Idempotent | Description |"
    echo "|---|---|---|---|"
    for snap in crates/calm-server/src/__toolsnaps__/*.snap; do
        name=$(jq -r '.name' "$snap")
        desc=$(jq -r '.description' "$snap" | tr '\n' ' ' | cut -c1-140)
        write=$(jq -r 'if .annotations.readOnlyHint == false then "yes" else "no" end' "$snap")
        idempotent=$(jq -r 'if .annotations.idempotentHint == false then "no" else "yes" end' "$snap")
        echo "| \`$name\` | $write | $idempotent | $desc |"
    done | LC_ALL=C sort
    echo
    echo "## Write-path taxonomy"
    echo
    echo "Tools with \`readOnlyHint: false\` -- the ones capable of touching disk or index"
    echo "state (see AGENTS.md's edit_context/diff_impact gate discipline for how their"
    echo "writes are reviewed):"
    echo
    for snap in crates/calm-server/src/__toolsnaps__/*.snap; do
        write=$(jq -r 'if .annotations.readOnlyHint == false then "yes" else "no" end' "$snap")
        if [ "$write" = "yes" ]; then
            echo "- \`$(jq -r '.name' "$snap")\`"
        fi
    done | LC_ALL=C sort
    echo
    echo "## Cargo feature flags (crates/calm-core)"
    echo
    awk '/^\[features\]/{flag=1; next} /^\[/{flag=0} flag && NF && $0 !~ /^#/' crates/calm-core/Cargo.toml \
        | sed -E 's/^([a-zA-Z0-9_-]+)[[:space:]]*=.*/- `\1`/' \
        | grep '^- `' \
        | LC_ALL=C sort
    echo
    echo "## Guarantee levels"
    echo
    echo "Hand-maintained in \`docs/guarantee-levels.toml\` (source of truth for the"
    echo "names/levels/evidence below); rendered here so a stale entry shows up in"
    echo "the same \`gen-status.sh --check\` drift gate a stale tool count would."
    echo "Level vocabulary is defined in that file's header comment."
    echo
    echo "| Behavior | Level | Summary |"
    echo "|---|---|---|"
    # Not a general TOML parser -- understands only this file's exact
    # repeated `[[behavior]]` + flat single-line `key = "value"` shape (see
    # that file's own header comment for the contract).
    awk '
        function emit() { if (id != "") printf "%s\t%s\t%s\n", id, level, summary }
        /^\[\[behavior\]\]/ { emit(); id=""; level=""; summary=""; next }
        /^id = / { id=$0; sub(/^id = "/, "", id); sub(/"[[:space:]]*$/, "", id) }
        /^level = / { level=$0; sub(/^level = "/, "", level); sub(/"[[:space:]]*$/, "", level) }
        /^summary = / { summary=$0; sub(/^summary = "/, "", summary); sub(/"[[:space:]]*$/, "", summary) }
        END { emit() }
    ' docs/guarantee-levels.toml \
        | LC_ALL=C sort \
        | while IFS=$'\t' read -r id level summary; do
            echo "| \`$id\` | \`$level\` | $summary |"
        done
} >"$tmp"

if [ "${1:-}" = "--check" ]; then
    if [ ! -f "$out" ] || ! diff -q "$tmp" "$out" >/dev/null 2>&1; then
        echo "gen-status: $out is stale -- run scripts/gen-status.sh to regenerate" >&2
        diff -u "$out" "$tmp" 2>/dev/null || true
        exit 1
    fi
    echo "gen-status: $out is up to date ($tool_count tools)."
    exit 0
fi

cp "$tmp" "$out"
echo "gen-status: wrote $out ($tool_count tools)."
